[package]
name = "simpleraytracer"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1"
gl = "*"
imagine = "0.0.5"

[dependencies.glfw]
version = "*"
default-features = false

[dev-dependencies]