[package]
name = "simpleraytracer"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1"
gl = "0.14.0"
imagine = "0.0.5"
log = "0.4.17"
pretty_env_logger = "0.4.0"
chrono = "0.4.23"

[dependencies.glfw]
version = "0.50.0"
default-features = false

[dependencies.opencl3]
version = "0.9.2"
features = ["CL_VERSION_2_1", "CL_VERSION_2_2", "CL_VERSION_3_0"]

[dev-dependencies]